name = "content-wizard"
compatibility_date = "2024-01-01"
main = "worker/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "content-assistant"
database_id = "YOUR_DATABASE_ID"

[vars]
ENVIRONMENT = "production"

[site]
bucket = "./dist"
