name = "content-wizard"
compatibility_date = "2024-01-01"
main = "worker/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "content-assistant"
database_id = "YOUR_DATABASE_ID"

[build]
command = "npm run build"

[site]
bucket = "./dist"

[dev]
port = 8787
