name = "content-wizard"
compatibility_date = "2024-01-01"
main = "worker/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "content-assistant"
database_id = "b365b64d-3595-4f95-adb7-470f570dc95c"

[build]
command = "npm run build"

[site]
bucket = "./dist"

[dev]
port = 8787
