name = "content-wizard"
compatibility_date = "2024-01-01"

[site]
source = "dist"
bucket = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "content_wizard_db"
database_id = "${DB_ID}"

[env.production]
d1_databases = [
  { binding = "DB", database_name = "content_wizard_db", database_id = "${DB_ID}" }
]

[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"