name = "content-wizard"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "content-assistant"
database_id = "YOUR_DATABASE_ID"

[vars]
ENVIRONMENT = "production"

[site]
Bucket = "./dist"
