name = "content-wizard-api"
main = "index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "content_wizard_db"
database_id = "${DB_ID}"

[vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "/api/*"
zone_name = "your-domain.com"

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.js"

[miniflare]
kv_persist = true
d1_persist = true